; ============================================================
; control.asm — Task 4: Control Structures Translator
; BIT 4220 Assembly Programming | x86-64 Linux
; ============================================================
;
; Shows how five common high-level control constructs map onto
; x86-64 CMP/JMP instructions.  The program is themed as a
; prepaid utility-meter control module.
;
;   Demo 1 — IF-ELSE   : cascaded comparisons + conditional jumps
;   Demo 2 — WHILE     : condition check at the TOP  (may run 0 times)
;   Demo 3 — DO-WHILE  : condition check at the BOTTOM (runs ≥ 1 time)
;   Demo 4 — FOR       : counter-controlled loop with known bounds
;   Demo 5 — SWITCH    : O(1) jump-table dispatch (as generated by compilers)
;
; BUILD
;   nasm -f elf64 control.asm -o control.o && ld control.o -o control
;   Or:  ./run.sh
; ============================================================

section .data

nl          db  0x0A

; ── Shared helpers ──────────────────────────────────────────
yes_s       db  "Yes", 0x0A
yes_slen    equ $ - yes_s
no_s        db  "No", 0x0A
no_slen     equ $ - no_s

; ── Banner + main menu ──────────────────────────────────────
banner      db  0x0A
            db  "============================================", 0x0A
            db  "  Task 4: Control Structures in Assembly   ", 0x0A
            db  "  BIT 4220 — Prepaid Meter Control Module  ", 0x0A
            db  "============================================", 0x0A
bannerlen   equ $ - banner

menu_txt    db  0x0A
            db  "  1) IF-ELSE    Balance classifier         ", 0x0A
            db  "  2) WHILE      Countdown loop             ", 0x0A
            db  "  3) DO-WHILE   Input validation           ", 0x0A
            db  "  4) FOR        Tariff rate table          ", 0x0A
            db  "  5) SWITCH     Device status dispatcher   ", 0x0A
            db  "  0) Exit", 0x0A
            db  0x0A
            db  "Choice: "
menutxtlen  equ $ - menu_txt

msg_inv     db  0x0A, "  Invalid choice. Enter 0-5.", 0x0A
msg_invlen  equ $ - msg_inv

msg_bye     db  0x0A, "  Goodbye!", 0x0A, 0x0A
msg_byelen  equ $ - msg_bye

; ── Demo 1 : IF-ELSE ────────────────────────────────────────
ife_hdr     db  0x0A, "-- Demo 1: IF-ELSE -- Balance Classifier --", 0x0A
ife_hdrlen  equ $ - ife_hdr
ife_prm     db  "  Enter balance (0-255): "
ife_prmlen  equ $ - ife_prm
ife_200     db  "  if   balance >= 200 ?  "
ife_200len  equ $ - ife_200
ife_100     db  "  elif balance >= 100 ?  "
ife_100len  equ $ - ife_100
ife_050     db  "  elif balance >=  50 ?  "
ife_050len  equ $ - ife_050
ife_else    db  "  else", 0x0A
ife_elselen equ $ - ife_else
ife_arrow   db  "  --> "
ife_arrowln equ $ - ife_arrow
ife_high    db  "HIGH    (balance >= 200)", 0x0A, 0x0A
ife_highlen equ $ - ife_high
ife_norm    db  "NORMAL  (100 <= balance < 200)", 0x0A, 0x0A
ife_normlen equ $ - ife_norm
ife_low     db  "LOW     (50 <= balance < 100)", 0x0A, 0x0A
ife_lowlen  equ $ - ife_low
ife_crit    db  "CRITICAL (balance < 50)", 0x0A, 0x0A
ife_critlen equ $ - ife_crit

; ── Demo 2 : WHILE ──────────────────────────────────────────
whl_hdr     db  0x0A, "-- Demo 2: WHILE -- Countdown Loop --", 0x0A
whl_hdrlen  equ $ - whl_hdr
whl_prm     db  "  Enter start value N (1-10): "
whl_prmlen  equ $ - whl_prm
whl_enter   db  "  [WHILE N > 0]", 0x0A
whl_enterln equ $ - whl_enter
whl_pfx     db  "    N = "
whl_pfxlen  equ $ - whl_pfx
whl_suf     db  " -- continue", 0x0A
whl_suflen  equ $ - whl_suf
whl_exit    db  "  [N = 0 : condition false -- loop exits]", 0x0A, 0x0A
whl_exitlen equ $ - whl_exit

; ── Demo 3 : DO-WHILE ───────────────────────────────────────
dwh_hdr     db  0x0A, "-- Demo 3: DO-WHILE -- Input Validation --", 0x0A
dwh_hdrlen  equ $ - dwh_hdr
dwh_note    db  "  [body runs BEFORE condition -- guaranteed at least once]", 0x0A
dwh_notelen equ $ - dwh_note
dwh_prm     db  "  [do] Enter value (1-5): "
dwh_prmlen  equ $ - dwh_prm
dwh_inv     db  "  [while: out of range -- repeat body]", 0x0A
dwh_invlen  equ $ - dwh_inv
dwh_ok      db  "  [while: in range -- exit loop]", 0x0A
dwh_oklen   equ $ - dwh_ok
dwh_acc     db  "  Accepted: "
dwh_acclen  equ $ - dwh_acc

; ── Demo 4 : FOR ────────────────────────────────────────────
for_hdr     db  0x0A, "-- Demo 4: FOR -- Tariff Rate Table --", 0x0A
for_hdrlen  equ $ - for_hdr
for_prm     db  "  Enter units N (1-9): "
for_prmlen  equ $ - for_prm
for_rate    db  "  Rate: 7 credits per unit", 0x0A
for_ratelen equ $ - for_rate
for_annot   db  "  [FOR i = 1; i <= N; i++]", 0x0A
for_annotln equ $ - for_annot
for_pfx     db  "    [i="
for_pfxlen  equ $ - for_pfx
for_mid     db  "]  "
for_midlen  equ $ - for_mid
for_creds   db  " credits", 0x0A
for_credsln equ $ - for_creds
for_end     db  "  [i > N -- loop done]", 0x0A, 0x0A
for_endlen  equ $ - for_end

; ── Demo 5 : SWITCH ─────────────────────────────────────────
swt_hdr     db  0x0A, "-- Demo 5: SWITCH -- Device Status Dispatcher --", 0x0A
swt_hdrlen  equ $ - swt_hdr
swt_prm     db  "  Enter status code (0-4): "
swt_prmlen  equ $ - swt_prm
swt_annot   db  "  [switch: O(1) jump-table dispatch]", 0x0A
swt_annotln equ $ - swt_annot
swt_c0      db  "  Case 0 -- OK:    meter operating normally.", 0x0A, 0x0A
swt_c0len   equ $ - swt_c0
swt_c1      db  "  Case 1 -- LOW:   recharge recommended.", 0x0A, 0x0A
swt_c1len   equ $ - swt_c1
swt_c2      db  "  Case 2 -- EMPTY: power supply suspended.", 0x0A, 0x0A
swt_c2len   equ $ - swt_c2
swt_c3      db  "  Case 3 -- FAULT: engineer call required.", 0x0A, 0x0A
swt_c3len   equ $ - swt_c3
swt_c4      db  "  Case 4 -- TEST:  diagnostic mode active.", 0x0A, 0x0A
swt_c4len   equ $ - swt_c4
swt_def     db  "  Default  -- UNKNOWN: unrecognised status code.", 0x0A, 0x0A
swt_deflen  equ $ - swt_def

; Jump table: 5 × 8-byte absolute addresses of case labels in .text
sw_jmptbl   dq  sw_case0, sw_case1, sw_case2, sw_case3, sw_case4

section .bss
    inbuf   resb 32         ; keyboard input (one byte at a time)
    numbuf  resb 24         ; decimal-to-ASCII scratch

section .text
    global _start

; ──────────────────────────────────────────────────────────────
_start:
    mov rsi, banner
    mov rdx, bannerlen
    call print_str

menu_loop:
    mov rsi, menu_txt
    mov rdx, menutxtlen
    call print_str

    call read_uint          ; choice → rax

    cmp rax, 5
    ja  .bad
    cmp rax, 0
    je  .bye
    cmp rax, 1
    je  if_else_demo
    cmp rax, 2
    je  while_demo
    cmp rax, 3
    je  do_while_demo
    cmp rax, 4
    je  for_demo
    jmp switch_demo         ; must be 5

.bad:
    mov rsi, msg_inv
    mov rdx, msg_invlen
    call print_str
    jmp menu_loop

.bye:
    mov rsi, msg_bye
    mov rdx, msg_byelen
    call print_str
    mov rax, 60
    xor rdi, rdi
    syscall

; ══════════════════════════════════════════════════════════════
; DEMO 1 — IF-ELSE
;
; High-level pseudocode:
;   if   balance >= 200:  print "HIGH"
;   elif balance >= 100:  print "NORMAL"
;   elif balance >=  50:  print "LOW"
;   else:                 print "CRITICAL"
;
; Assembly pattern
;   Each condition that FAILS falls through to the next CMP.
;   A condition that PASSES jumps to its result block, prints,
;   then jumps to the end.  This is a direct linear translation.
;
; Instruction-pointer trace (balance = 150):
;   CMP 150,200 → JGE .high NOT taken → fall through
;   CMP 150,100 → JGE .norm TAKEN → IP jumps to .norm
;   → prints NORMAL → JMP menu_loop
; ══════════════════════════════════════════════════════════════
if_else_demo:
    mov rsi, ife_hdr
    mov rdx, ife_hdrlen
    call print_str

    mov rsi, ife_prm
    mov rdx, ife_prmlen
    call print_str
    call read_uint                  ; balance → rax

    ; ── if balance >= 200 ──────────────────────────────────
    mov rsi, ife_200
    mov rdx, ife_200len
    call print_str                  ; show condition being tested
    cmp rax, 200
    jge .high                       ; YES: jump to HIGH block
    mov rsi, no_s                   ; NO:  print "No" and fall through
    mov rdx, no_slen
    call print_str

    ; ── elif balance >= 100 ────────────────────────────────
    mov rsi, ife_100
    mov rdx, ife_100len
    call print_str
    cmp rax, 100
    jge .norm
    mov rsi, no_s
    mov rdx, no_slen
    call print_str

    ; ── elif balance >= 50 ─────────────────────────────────
    mov rsi, ife_050
    mov rdx, ife_050len
    call print_str
    cmp rax, 50
    jge .low
    mov rsi, no_s
    mov rdx, no_slen
    call print_str

    ; ── else ───────────────────────────────────────────────
    mov rsi, ife_else
    mov rdx, ife_elselen
    call print_str
    mov rsi, ife_arrow
    mov rdx, ife_arrowln
    call print_str
    mov rsi, ife_crit
    mov rdx, ife_critlen
    call print_str
    jmp menu_loop

.high:
    mov rsi, yes_s
    mov rdx, yes_slen
    call print_str
    mov rsi, ife_arrow
    mov rdx, ife_arrowln
    call print_str
    mov rsi, ife_high
    mov rdx, ife_highlen
    call print_str
    jmp menu_loop

.norm:
    mov rsi, yes_s
    mov rdx, yes_slen
    call print_str
    mov rsi, ife_arrow
    mov rdx, ife_arrowln
    call print_str
    mov rsi, ife_norm
    mov rdx, ife_normlen
    call print_str
    jmp menu_loop

.low:
    mov rsi, yes_s
    mov rdx, yes_slen
    call print_str
    mov rsi, ife_arrow
    mov rdx, ife_arrowln
    call print_str
    mov rsi, ife_low
    mov rdx, ife_lowlen
    call print_str
    jmp menu_loop

; ══════════════════════════════════════════════════════════════
; DEMO 2 — WHILE
;
; High-level pseudocode:
;   N = input
;   while N > 0:
;       print N
;       N -= 1
;
; Assembly pattern
;   CMP is at the TOP of the loop.
;   JLE skips past the body when the condition is false.
;   The body ends with an unconditional JMP back to the CMP.
;   Key difference from do-while: body may execute ZERO times.
;
; Instruction-pointer trace (N = 2):
;   CMP 2,0 → JLE NOT taken → body → DEC → JMP .top
;   CMP 1,0 → JLE NOT taken → body → DEC → JMP .top
;   CMP 0,0 → JLE TAKEN → IP jumps past body to .whl_done
; ══════════════════════════════════════════════════════════════
while_demo:
    mov rsi, whl_hdr
    mov rdx, whl_hdrlen
    call print_str

    mov rsi, whl_prm
    mov rdx, whl_prmlen
    call print_str
    call read_uint
    and rax, 0xF                    ; cap at 15 to limit output
    mov rcx, rax                    ; N → rcx  (preserved by helpers)

    mov rsi, whl_enter
    mov rdx, whl_enterln
    call print_str

    ; ── WHILE loop ─────────────────────────────────────────
.top:
    cmp rcx, 0                      ; condition: N > 0 ?
    jle .whl_done                   ; NO → skip body, exit loop

    ; body
    mov rsi, whl_pfx
    mov rdx, whl_pfxlen
    call print_str                  ; "    N = "
    mov rax, rcx
    call print_uint_noeol
    mov rsi, whl_suf
    mov rdx, whl_suflen
    call print_str                  ; " -- continue\n"

    dec rcx                         ; N -= 1
    jmp .top                        ; back to condition check
    ; ── end WHILE ──────────────────────────────────────────

.whl_done:
    mov rsi, whl_exit
    mov rdx, whl_exitlen
    call print_str
    jmp menu_loop

; ══════════════════════════════════════════════════════════════
; DEMO 3 — DO-WHILE
;
; High-level pseudocode:
;   do:
;       n = read_input()
;   while n < 1 or n > 5
;   print "Accepted:", n
;
; Assembly pattern
;   Body label is the TOP of the loop — no pre-check.
;   CMP is at the BOTTOM; a true condition jumps back to body.
;   A false condition falls through (exits loop).
;   Key difference from while: body ALWAYS runs at least once.
;
; Instruction-pointer trace (enters 0, then 3):
;   .body → read 0 → CMP 0,1 → JB .body (repeat)
;   .body → read 3 → CMP 3,1 → JB NOT taken
;            CMP 3,5 → JA NOT taken → fall through → exit
; ══════════════════════════════════════════════════════════════
do_while_demo:
    mov rsi, dwh_hdr
    mov rdx, dwh_hdrlen
    call print_str

    mov rsi, dwh_note
    mov rdx, dwh_notelen
    call print_str

    ; ── DO-WHILE loop ──────────────────────────────────────
.body:                              ; ← loop top (no condition here!)
    mov rsi, dwh_prm
    mov rdx, dwh_prmlen
    call print_str
    call read_uint                  ; n → rax  (print_str preserved it)

    ; condition check at BOTTOM
    cmp rax, 1
    jb  .repeat                     ; n < 1: true → repeat
    cmp rax, 5
    ja  .repeat                     ; n > 5: true → repeat

    ; condition false → exit loop
    mov rsi, dwh_ok
    mov rdx, dwh_oklen
    call print_str
    jmp .accept

.repeat:
    mov rsi, dwh_inv
    mov rdx, dwh_invlen
    call print_str
    jmp .body                       ; ← loop back (condition was true)
    ; ── end DO-WHILE ───────────────────────────────────────

.accept:
    ; rax = valid n (print_str preserves rax; no clobber since accept)
    mov rsi, dwh_acc
    mov rdx, dwh_acclen
    call print_str
    call print_uint
    jmp menu_loop

; ══════════════════════════════════════════════════════════════
; DEMO 4 — FOR
;
; High-level pseudocode:
;   rate = 7
;   for i = 1 to N:
;       print i, "units ->", i*rate, "credits"
;
; Assembly pattern
;   Identical structure to WHILE but convention names the three
;   parts: initialiser (MOV rcx,1), condition (CMP rcx,rbx),
;   and increment (INC rcx).  They map to the three clauses of
;   a C-style for(...;...;...) statement.
;
; Instruction-pointer trace (N = 3):
;   MOV rcx,1 → CMP 1,3 → JG NOT taken → body → INC → JMP .for_top
;               CMP 2,3 → JG NOT taken → body → INC → JMP .for_top
;               CMP 3,3 → JG NOT taken → body → INC → JMP .for_top
;               CMP 4,3 → JG TAKEN → IP jumps to .for_done
; ══════════════════════════════════════════════════════════════
for_demo:
    mov rsi, for_hdr
    mov rdx, for_hdrlen
    call print_str

    mov rsi, for_prm
    mov rdx, for_prmlen
    call print_str
    call read_uint
    and rax, 0xF                    ; cap at 15
    test rax, rax
    jz  .for_skip                   ; N = 0: nothing to print
    mov rbx, rax                    ; N → rbx (preserved by helpers)

    mov rsi, for_rate
    mov rdx, for_ratelen
    call print_str

    mov rsi, for_annot
    mov rdx, for_annotln
    call print_str

    ; ── FOR loop ───────────────────────────────────────────
    mov rcx, 1                      ; i = 1  (initialiser)

.for_top:
    cmp rcx, rbx                    ; i <= N ?  (condition)
    jg  .for_done                   ; NO → exit loop

    ; body
    mov rsi, for_pfx
    mov rdx, for_pfxlen
    call print_str                  ; "    [i="
    mov rax, rcx
    call print_uint_noeol           ; i
    mov rsi, for_mid
    mov rdx, for_midlen
    call print_str                  ; "]  "
    imul rax, rcx, 7               ; cost = i*7  (rcx not clobbered)
    call print_uint_noeol           ; cost
    mov rsi, for_creds
    mov rdx, for_credsln
    call print_str                  ; " credits\n"

    inc rcx                         ; i++  (increment)
    jmp .for_top                    ; back to condition
    ; ── end FOR ────────────────────────────────────────────

.for_done:
    mov rsi, for_end
    mov rdx, for_endlen
    call print_str

.for_skip:
    jmp menu_loop

; ══════════════════════════════════════════════════════════════
; DEMO 5 — SWITCH-CASE
;
; High-level pseudocode:
;   switch code:
;       case 0: "OK"      case 1: "LOW"
;       case 2: "EMPTY"   case 3: "FAULT"
;       case 4: "TEST"    default: "UNKNOWN"
;
; Assembly pattern — JUMP TABLE (compiler-generated form)
;   For a dense integer range 0..N, an optimising compiler builds
;   a table of N+1 code addresses.  One bounds-check guards the
;   table; then a single indirect JMP dispatches to the case:
;       JMP [table + code*8]
;   This is O(1) regardless of the number of cases.  A
;   compare-chain would be O(n).
;
;   The table sw_jmptbl lives in .data and holds the 64-bit
;   virtual addresses of the case labels in .text (filled in by
;   the linker at link time).
;
; Instruction-pointer trace (code = 2):
;   CMP 2,4  → JA NOT taken (in range)
;   LEA rbx, [sw_jmptbl]    → rbx = &table
;   JMP [rbx + 2*8]         → IP = table[2] = address of sw_case2
;   → prints EMPTY
;   JMP sw_done → JMP menu_loop
; ══════════════════════════════════════════════════════════════
switch_demo:
    mov rsi, swt_hdr
    mov rdx, swt_hdrlen
    call print_str

    mov rsi, swt_prm
    mov rdx, swt_prmlen
    call print_str
    call read_uint                  ; code → rax

    mov rsi, swt_annot
    mov rdx, swt_annotln
    call print_str

    ; ── SWITCH dispatch ────────────────────────────────────
    cmp rax, 4                      ; valid range 0-4?
    ja  sw_default                  ; out of range → default

    lea rbx, [sw_jmptbl]            ; base address of jump table
    jmp [rbx + rax*8]              ; indirect jump: table[code]
    ; ── end SWITCH ─────────────────────────────────────────

sw_case0:
    mov rsi, swt_c0
    mov rdx, swt_c0len
    call print_str
    jmp sw_done

sw_case1:
    mov rsi, swt_c1
    mov rdx, swt_c1len
    call print_str
    jmp sw_done

sw_case2:
    mov rsi, swt_c2
    mov rdx, swt_c2len
    call print_str
    jmp sw_done

sw_case3:
    mov rsi, swt_c3
    mov rdx, swt_c3len
    call print_str
    jmp sw_done

sw_case4:
    mov rsi, swt_c4
    mov rdx, swt_c4len
    call print_str
    jmp sw_done

sw_default:
    mov rsi, swt_def
    mov rdx, swt_deflen
    call print_str

sw_done:
    jmp menu_loop

; ──────────────────────────────────────────────────────────────
; print_str — sys_write(stdout, rsi, rdx)
;   Saves and restores rax and rdi.
;   The syscall instruction itself clobbers rcx and r11.
; ──────────────────────────────────────────────────────────────
print_str:
    push rax
    push rdi
    mov rax, 1              ; sys_write
    mov rdi, 1              ; fd = stdout
    syscall
    pop rdi
    pop rax
    ret

; ──────────────────────────────────────────────────────────────
; print_uint — print rax as unsigned decimal followed by newline
; ──────────────────────────────────────────────────────────────
print_uint:
    call print_uint_noeol
    push rsi
    push rdx
    mov rsi, nl
    mov rdx, 1
    call print_str
    pop rdx
    pop rsi
    ret

; ──────────────────────────────────────────────────────────────
; print_uint_noeol — print rax as unsigned decimal, no newline
;   Preserves: rbx, rcx, rdx, rdi
; ──────────────────────────────────────────────────────────────
print_uint_noeol:
    push rbx
    push rcx
    push rdx
    push rdi

    test rax, rax
    jnz .nonzero
    lea rsi, [numbuf]
    mov byte [rsi], '0'
    mov rdx, 1
    call print_str
    jmp .done

.nonzero:
    mov rbx, 10
    xor rcx, rcx
    lea rdi, [numbuf + 23]          ; build string right-to-left
.digit:
    xor rdx, rdx
    div rbx                         ; rdx = digit, rax = quotient
    add dl, '0'
    mov [rdi], dl
    dec rdi
    inc rcx
    test rax, rax
    jnz .digit
    inc rdi                         ; rdi → most-significant digit
    mov rsi, rdi
    mov rdx, rcx
    call print_str

.done:
    pop rdi
    pop rdx
    pop rcx
    pop rbx
    ret

; ──────────────────────────────────────────────────────────────
; read_uint — read ASCII decimal from stdin, return value in rax
;   Reads one byte at a time until LF or EOF.
;   Skips CR and non-digit characters.
;   Uses IMUL (not MUL) because syscall clobbers RCX so a
;   multiplier stored there would need reloading every iteration.
; ──────────────────────────────────────────────────────────────
read_uint:
    push rbx
    push rsi
    push rdi

    xor rbx, rbx                    ; accumulator = 0

.next:
    mov rax, 0                      ; sys_read
    mov rdi, 0                      ; stdin
    lea rsi, [inbuf]
    mov rdx, 1
    syscall
    test rax, rax
    jle .done_r                     ; EOF or error

    movzx rax, byte [inbuf]
    cmp al, 0x0A
    je  .done_r                     ; LF: end of input
    cmp al, 0x0D
    je  .next                       ; CR: skip
    cmp al, '0'
    jb  .next                       ; non-digit: skip
    cmp al, '9'
    ja  .next

    sub al, '0'                     ; digit value 0-9
    push rax                        ; save digit
    imul rbx, rbx, 10              ; accumulator × 10 (no rdx clobber)
    pop rax
    add rbx, rax                    ; accumulator = accumulator×10 + digit
    jmp .next

.done_r:
    mov rax, rbx

    pop rdi
    pop rsi
    pop rbx
    ret
